// Starwood (starwood.com.tr/detay.php?PageName=dekorlar) dekor kataloğundan alınmıştır.
// Görseller frontend public/decors klasöründe barındırılıyor.
const mdfLamDecors = [
  { name: "AVUSTRALYA", category: "Ahşap", code: "332/SENKRON", imageUrl: "/decors/ahsap-avustralya.jpg" },
  { name: "AMERİKA", category: "Ahşap", code: "329/SENKRON", imageUrl: "/decors/ahsap-amerika.jpg" },
  { name: "ASYA", category: "Ahşap", code: "328/SENKRON", imageUrl: "/decors/ahsap-asya.jpg" },
  { name: "SÜMELA", category: "Ahşap", code: "83/NATUREL", imageUrl: "/decors/ahsap-sumela.jpg" },
  { name: "SANDIK", category: "Ahşap", code: "290/DERİN", imageUrl: "/decors/ahsap-sandik.jpg" },
  { name: "İYONYA", category: "Ahşap", code: "309/WOOD", imageUrl: "/decors/ahsap-iyonya.jpg" },
  { name: "KALEMİŞİ", category: "Ahşap", code: "182/KEPİ", imageUrl: "/decors/ahsap-kalemisi.jpg" },
  { name: "PEKİN", category: "Ahşap", code: "144/KEPİ", imageUrl: "/decors/ahsap-pekin.jpg" },
  { name: "EBRU", category: "Ahşap", code: "181/KEPİ", imageUrl: "/decors/ahsap-ebru.jpg" },
  { name: "ANTİK LİGHT", category: "Ahşap", code: "52/DERİN", imageUrl: "/decors/ahsap-antik-light.jpg" },
  { name: "BATUM VENGE", category: "Ahşap", code: "28/DERİN", imageUrl: "/decors/ahsap-batum-venge.jpg" },
  { name: "SAFİR MEŞE", category: "Ahşap", code: "102/FREZE", imageUrl: "/decors/ahsap-safir-mese.jpg" },
  { name: "İSTANBUL", category: "Ahşap", code: "103/DÜZ", imageUrl: "/decors/ahsap-istanbul.jpg" },
  { name: "LİZBON", category: "Ahşap", code: "143/KEPİ", imageUrl: "/decors/ahsap-lizbon.jpg" },
  { name: "MİNYATÜR", category: "Ahşap", code: "180/WOOD", imageUrl: "/decors/ahsap-minyatur.jpg" },
  { name: "AÇIK HARELİ CEVİZ", category: "Ahşap", code: "53/BUTE", imageUrl: "/decors/ahsap-acik-hareli-ceviz.jpg" },
  { name: "HARELİ CEVİZ", category: "Ahşap", code: "72/BUTE", imageUrl: "/decors/ahsap-hareli-ceviz.jpg" },
  { name: "HATTUŞA", category: "Ahşap", code: "304/DERİN", imageUrl: "/decors/ahsap-hattusa.jpg" },
  { name: "SONOMO", category: "Ahşap", code: "17/SÜPERMAT", imageUrl: "/decors/ahsap-sonomo.jpg" },
  { name: "AVUSTRALYA CEVİZ", category: "Ahşap", code: "69/DERİN", imageUrl: "/decors/ahsap-avustralya-ceviz.jpg" },
  { name: "BALABAN", category: "Ahşap", code: "317/GÖLGE", imageUrl: "/decors/ahsap-balaban.jpg" },
  { name: "DÜNYA", category: "Ahşap", code: "331/SENKRON", imageUrl: "/decors/ahsap-dunya.jpg" },
  { name: "ANTARTİKA", category: "Ahşap", code: "330/SENKRON", imageUrl: "/decors/ahsap-antartika.jpg" },
  { name: "AVRUPA", category: "Ahşap", code: "326/SENKRON", imageUrl: "/decors/ahsap-avrupa.jpg" },
  { name: "AFRİKA", category: "Ahşap", code: "327/SENKRON", imageUrl: "/decors/ahsap-afrika.jpg" },
  { name: "SARDES", category: "Ahşap", code: "310/DERİN", imageUrl: "/decors/ahsap-sardes.jpg" },
  { name: "HAT", category: "Ahşap", code: "314/DERİN", imageUrl: "/decors/ahsap-hat.jpg" },
  { name: "RAHLE", category: "Ahşap", code: "291/DERİN", imageUrl: "/decors/ahsap-rahle.jpg" },
  { name: "ZAMBAK", category: "Ahşap", code: "318/DERİN", imageUrl: "/decors/ahsap-zambak.jpg" },
  { name: "TESBİH", category: "Ahşap", code: "282/DERİN", imageUrl: "/decors/ahsap-tesbih.jpg" },
  { name: "KEMENÇE", category: "Ahşap", code: "294/DERİN", imageUrl: "/decors/ahsap-kemence.jpg" },
  { name: "UD", category: "Ahşap", code: "297/DERİN", imageUrl: "/decors/ahsap-ud.jpg" },
  { name: "TUŞPA", category: "Ahşap", code: "308/DERİN", imageUrl: "/decors/ahsap-tuspa.jpg" },
  { name: "FLORANSA", category: "Ahşap", code: "137/SÜPERMAT", imageUrl: "/decors/ahsap-floransa.jpg" },
  { name: "SEPET", category: "Ahşap", code: "293/DERİN", imageUrl: "/decors/ahsap-sepet.jpg" },
  { name: "ASUR", category: "Ahşap", code: "112/GÖLGE", imageUrl: "/decors/ahsap-asur.jpg" },
  { name: "SOFYA", category: "Ahşap", code: "147/KEPİ", imageUrl: "/decors/ahsap-sofya.jpg" },
  { name: "HİTİT", category: "Ahşap", code: "306/KEPİ", imageUrl: "/decors/ahsap-hitit.jpg" },
  { name: "LİDYA", category: "Ahşap", code: "301/KEPİ", imageUrl: "/decors/ahsap-lidya.jpg" },
  { name: "KELEBEK", category: "Ahşap", code: "324/GÖLGE", imageUrl: "/decors/ahsap-kelebek.jpg" },
  { name: "KAPLAN", category: "Ahşap", code: "321/GÖLGE", imageUrl: "/decors/ahsap-kaplan.jpg" },
  { name: "LOTUS", category: "Ahşap", code: "319/KEPİ", imageUrl: "/decors/ahsap-lotus.jpg" },
  { name: "DENİZ FENERİ", category: "Ahşap", code: "63/GÖLGE", imageUrl: "/decors/ahsap-deniz-feneri.jpg" },
  { name: "RIHTIM", category: "Ahşap", code: "22/GÖLGE", imageUrl: "/decors/ahsap-rihtim.jpg" },
  { name: "KORİNT", category: "Ahşap", code: "29/GÖLGE", imageUrl: "/decors/ahsap-korint.jpg" },
  { name: "KEŞİF", category: "Ahşap", code: "193/DERİN", imageUrl: "/decors/ahsap-kesif.jpg" },
  { name: "UFUK", category: "Ahşap", code: "185/KEPİ", imageUrl: "/decors/ahsap-ufuk.jpg" },
  { name: "ZİRVE", category: "Ahşap", code: "184/DERİN", imageUrl: "/decors/ahsap-zirve.jpg" },
  { name: "PUSULA", category: "Ahşap", code: "189/GÖLGE", imageUrl: "/decors/ahsap-pusula.jpg" },
  { name: "ROTA", category: "Ahşap", code: "188/GÖLGE", imageUrl: "/decors/ahsap-rota.jpg" },
  { name: "LEOPAR", category: "Ahşap", code: "68/SÜPERMAT", imageUrl: "/decors/ahsap-leopar.jpg" },
  { name: "BEYRUT", category: "Ahşap", code: "61/GÖLGE", imageUrl: "/decors/ahsap-beyrut.jpg" },
  { name: "LAKE GRİ", category: "Düz Renkler", code: "159/SENKRON-DÜZ-PARLAK", imageUrl: "/decors/duz-renkler-lake-gri.jpg" },
  { name: "DOLUNAY", category: "Düz Renkler", code: "161/SENKRON", imageUrl: "/decors/duz-renkler-dolunay.jpg" },
  { name: "İPEK SİYAH", category: "Düz Renkler", code: "160/SENKRON-NATUREL", imageUrl: "/decors/duz-renkler-ipek-siyah.jpg" },
  { name: "TOPAZ", category: "Düz Renkler", code: "104/GÖLGE", imageUrl: "/decors/duz-renkler-topaz.jpg" },
  { name: "LÜLETAŞI", category: "Düz Renkler", code: "108/GÖLGE", imageUrl: "/decors/duz-renkler-luletasi.jpg" },
  { name: "POMZA", category: "Düz Renkler", code: "105/GÖLGE", imageUrl: "/decors/duz-renkler-pomza.jpg" },
  { name: "GÜMÜŞ", category: "Düz Renkler", code: "111/GÖLGE", imageUrl: "/decors/duz-renkler-gumus.jpg" },
  { name: "KOBALT", category: "Düz Renkler", code: "110/GÖLGE", imageUrl: "/decors/duz-renkler-kobalt.jpg" },
  { name: "KUVARS", category: "Düz Renkler", code: "107/GÖLGE", imageUrl: "/decors/duz-renkler-kuvars.jpg" },
  { name: "KARBEYAZ", category: "Düz Renkler", code: "66/DÜZ-PARLAK", imageUrl: "/decors/duz-renkler-karbeyaz.jpg" },
  { name: "KIRMIZI", category: "Düz Renkler", code: "56/DÜZ", imageUrl: "/decors/duz-renkler-kirmizi.jpg" },
  { name: "KUMSAL", category: "Düz Renkler", code: "40/DÜZ-GÖLGE-PARLAK-SENKRON", imageUrl: "/decors/duz-renkler-kumsal.jpg" },
  { name: "ATLAS", category: "Düz Renkler", code: "44/DÜZ-GÖLGE-SENKRON-PARLAK", imageUrl: "/decors/duz-renkler-atlas.jpg" },
  { name: "KUMTAŞI", category: "Düz Renkler", code: "139/DÜZ-NATUREL-PARLAK", imageUrl: "/decors/duz-renkler-kumtasi.jpg" },
  { name: "DOLUNAY", category: "Düz Renkler", code: "161/DÜZ-PARLAK", imageUrl: "/decors/duz-renkler-dolunay-2.jpg" },
  { name: "VİZON BEJ", category: "Düz Renkler", code: "170/DÜZ-PARLAK", imageUrl: "/decors/duz-renkler-vizon-bej.jpg" },
  { name: "ELVİRA BEJ", category: "Düz Renkler", code: "58/PARLAK", imageUrl: "/decors/duz-renkler-elvira-bej.jpg" },
  { name: "AYTAŞI", category: "Düz Renkler", code: "138/DÜZ-PARLAK-WOOD-SENKRON", imageUrl: "/decors/duz-renkler-aytasi.jpg" },
  { name: "YAPRAK", category: "Düz Renkler", code: "325/GÖLGE", imageUrl: "/decors/duz-renkler-yaprak.jpg" },
  { name: "DENİZ YILDIZI", category: "Düz Renkler", code: "121/DİNAMİK", imageUrl: "/decors/duz-renkler-deniz-yildizi.jpg" },
  { name: "İNCİ", category: "Düz Renkler", code: "120/DİNAMİK", imageUrl: "/decors/duz-renkler-inci.jpg" },
  { name: "DENİZ KABUĞU", category: "Düz Renkler", code: "119/DİNAMİK", imageUrl: "/decors/duz-renkler-deniz-kabugu.jpg" },
  { name: "LAGÜN", category: "Düz Renkler", code: "116/DİNAMİK", imageUrl: "/decors/duz-renkler-lagun.jpg" },
  { name: "İSTİRİDYE", category: "Düz Renkler", code: "115/DİNAMİK", imageUrl: "/decors/duz-renkler-istiridye.jpg" },
  { name: "ANEMON", category: "Düz Renkler", code: "114/DİNAMİK", imageUrl: "/decors/duz-renkler-anemon.jpg" },
  { name: "YOSUN", category: "Düz Renkler", code: "113/DİNAMİK", imageUrl: "/decors/duz-renkler-yosun.jpg" },
  { name: "SİYAH", category: "Düz Renkler", code: "2/PARLAK-SENKRON-BUTE", imageUrl: "/decors/duz-renkler-siyah.jpg" },
  { name: "BEJ", category: "Düz Renkler", code: "7/PARLAK-BUTE", imageUrl: "/decors/duz-renkler-bej.jpg" },
  { name: "GRİ 3414", category: "Düz Renkler", code: "11/BUTE", imageUrl: "/decors/duz-renkler-gri-3414.jpg" },
  { name: "ANTRASİT GRİ", category: "Düz Renkler", code: "275/NATUREL", imageUrl: "/decors/duz-renkler-antrasit-gri.jpg" },
  { name: "MERCAN", category: "Düz Renkler", code: "122/DİNAMİK", imageUrl: "/decors/duz-renkler-mercan.jpg" },
  { name: "RESİF", category: "Düz Renkler", code: "118/DİNAMİK", imageUrl: "/decors/duz-renkler-resif.jpg" },
  { name: "SÜNGER", category: "Düz Renkler", code: "117/DİNAMİK", imageUrl: "/decors/duz-renkler-sunger.jpg" },
];

module.exports = mdfLamDecors;